#SERVER_PRIVATE_DER_FILE = "priv.der"
#SERVER_PUBLIC_DER_FILE = "pub.der"

SERVER_PRIVATE_DER_FILE = "private_key.der"
SERVER_PUBLIC_DER_FILE = "public_key.der"

SIGNATURE_LENGTH = 256
EKEY_LENGTH = 256
NONCE_LENGTH = 16
AES_KEY_LENGTH = 32
AES_IV_LENGTH = 16
AES_TAG_LENGTH = 16
RSA_KEY_LENGTH = 2048
TIMESTAMP_LENGTH = 4
LEN_LENGTH = 2

DB_LOCATION = "user.db"
CONFIG_FILE = "config.json"
